#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MVVMCalc.Droid.Resource", IsApplication=true)]

namespace MVVMCalc.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::MVVMCalc.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::MVVMCalc.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::MVVMCalc.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::MVVMCalc.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::MVVMCalc.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::MVVMCalc.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::MVVMCalc.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::MVVMCalc.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::MVVMCalc.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::MVVMCalc.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::MVVMCalc.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::MVVMCalc.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::MVVMCalc.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::MVVMCalc.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::MVVMCalc.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::MVVMCalc.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::MVVMCalc.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::MVVMCalc.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::MVVMCalc.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::MVVMCalc.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::MVVMCalc.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.ApplicationName = global::MVVMCalc.Droid.Resource.String.ApplicationName;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.Hello = global::MVVMCalc.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MVVMCalc.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MVVMCalc.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int androidcolors = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070002
			public const int dirty_blue = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int dirty_green = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int dirty_red = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int transparent = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_android_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_directions_boat_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_do_not_disturb_on_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MvvmCrossTagId = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MvxBindingTagUnique = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int checkBoxBoy = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int checkBoxCat = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int checkBoxDog = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int checkBoxGirl = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int editTextAge = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int editTextKids = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int editTextName = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int itemCalc = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int ll = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int menuClear = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int menuItem = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int radioButtonCareer = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int radioButtonFamily = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int radioButtonYourself = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int rowAge = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int rowAnsver = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int rowName = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int sv = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CalcView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cell_layout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int result_layout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SplashScreen = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int menu_result = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int Age = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int Ansver1 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int Ansver2 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int Ansver31 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int Ansver32 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int Ansver4 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int Ansver5 = 2131034137;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int Back = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int Boy = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int Career = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int Cat = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int Clean = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int Default = 2131034131;
			
			// aapt resource value: 0x7f050006
			public const int Dog = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int Family = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int Girl = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int IsMarried = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int Kids = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int Name = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int Partner = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int Pet = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int Prioryty = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int Result = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int Yourself = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int menuItem = 2131034138;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int EnterFild = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int LabelSize = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int LeftTextSize = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int TextSize = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
