#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CalcSW.Resource", IsApplication=true)]

namespace CalcSW
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int androidcolors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int dirty_blue = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int dirty_green = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int dirty_red = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_android_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_directions_boat_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_do_not_disturb_on_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000a
			public const int checkBoxBoy = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int checkBoxCat = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int checkBoxDog = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int checkBoxGirl = 2131296265;
			
			// aapt resource value: 0x7f090006
			public const int editTextAge = 2131296262;
			
			// aapt resource value: 0x7f09000b
			public const int editTextKids = 2131296267;
			
			// aapt resource value: 0x7f090005
			public const int editTextName = 2131296261;
			
			// aapt resource value: 0x7f090010
			public const int emptyText = 2131296272;
			
			// aapt resource value: 0x7f090013
			public const int itemCalc = 2131296275;
			
			// aapt resource value: 0x7f09000f
			public const int listResult = 2131296271;
			
			// aapt resource value: 0x7f090012
			public const int menuClear = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int menuItem = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int radioButtonCareer = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int radioButtonFamily = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int radioButtonYourself = 2131296270;
			
			// aapt resource value: 0x7f090001
			public const int rowAge = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int rowAnsver = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int rowName = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int textResult = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int textView1 = 2131296259;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int cell_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_default = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int result_layout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int menu_result = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060004
			public const int Age = 2131099652;
			
			// aapt resource value: 0x7f060014
			public const int Ansver1 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int Ansver2 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int Ansver31 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int Ansver32 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int Ansver4 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int Ansver5 = 2131099673;
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int Back = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int Boy = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int Career = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int Cat = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int Clean = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int Default = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int Dog = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int Family = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int Girl = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int IsMarried = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int Kids = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int Name = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int Partner = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int Pet = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int Prioryty = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int Result = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int Yourself = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int menuItem = 2131099674;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int EnterFild = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int LabelSize = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int LeftTextSize = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int TextSize = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
