#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CSW.Resource", IsApplication=true)]

namespace CSW
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_android_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_directions_boat_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int checkBoxBoy = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int checkBoxCat = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int checkBoxDog = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int checkBoxGirl = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int editTextAge = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int editTextKids = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int editTextName = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout2 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout3 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout4 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout5 = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int menuItem = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int radioButtonCareer = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int radioButtonFamily = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int radioButtonYourself = 2131099667;
			
			// aapt resource value: 0x7f06000f
			public const int radioGroup1 = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int textView13 = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int textView3 = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int textViewRsult = 2131099668;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int Age = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int Ansver1 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int Ansver2 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int Ansver31 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int Ansver32 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int Ansver4 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int Ansver5 = 2130968597;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int Boy = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int Career = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int Cat = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int Dog = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int Family = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int Girl = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int IsMarried = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int Kids = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int Name = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int Partner = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int Pet = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int Prioryty = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int Yourself = 2130968590;
			
			// aapt resource value: 0x7f040016
			public const int menuItem = 2130968598;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
